---
### Updates the IP address of the bastion / Admin jumpbox in the role configuration file
### example:
### ansible-playbook ec2_update_bastion_address.yml -e "ec2_region=us-east-1 ec2_role=WPServer ec2_bastion_role=AdminJumpbox"

- hosts: localhost
  connection: local
  gather_facts: false
  user: root
  pre_tasks:
    - name: Reads bastion role variables
      include_vars:
        dir: roles/
        files_matching: "{{ ec2_bastion_role }}.yml"

  tasks:
    - name: Get EC2 public IP 
      run_once: true
      ec2_instance_facts:
        region: "{{ ec2_region }}"
        filters:
          "tag:Role": "{{ec2_bastion_role}}"
          "instance-state-name": running
      register: instances

    - name: "List Instances IPs for {{ ec2_bastion_role }}"
      debug:
        msg: "Instance IP: {{ item }}"
      with_items: "{{instances|json_query('instances[*].public_ip_address') | list | unique}}"

    - name: "Saves the public IP of the bastion to roles/{{ ec2_role }}.yml"
      lineinfile:
        path: "roles/{{ ec2_role }}.yml"
        regexp: '^ec2_bastion: .*$'
        line: "ec2_bastion: {{ instances|json_query('instances[*].public_ip_address') | list | first}}"
