---
### provision AWS EC2 instance into a specified region and role configured in an instance type
### example:
### ansible-playbook ec2_provision_by_region_role.yml -e "ec2_region=us-east-1 ec2_role=AdminJumpbox"
### the secuity group is optional, but might be a good idea or it can be instantiated in the default, making it hard to deal with later
### to deploy in multiple AZs, specify multiple subnets
### ansible-playbook ec2_provision_by_region_role.yml -e "ec2_region=us-east-1 ec2_role=AdminJumpbox ec2_sg=AdminSecurityGroup"
### the ec2_role is also a file suffix that points to a yml file within roles directory
### This will loop through each subnet for the role and create count_tag instances there

- hosts: localhost
  connection: local
  gather_facts: false
  remote_user: ec2-user
  pre_tasks:
    - name: Reads role variables
      include_vars:
        dir: roles/
        files_matching: "{{ ec2_role }}.yml"
    - name: Reads Security Group variables conditionally, needs ec2_sg parameter
      include_vars:
        dir: networks/
        files_matching: "{{ ec2_sg }}.yml"
      when: ec2_sg is defined
  tasks:
    - name: "Get Subnets for {{ ec2_role }}"
      ec2_vpc_subnet_facts:
        region: "{{ ec2_region }}"
        filters:
          "tag:Role": "{{ ec2_role }}"
      register: mysubnets

    - name: Provision {{ ec2_count }} instances with role tag {{ ec2_role }}
      local_action:
        module: ec2
        key_name: "{{ ec2_keypair }}"
        # If specified a Scurity Group will be added, or else, omitted
        # It sucks because once you create a Classic EC2 (non-VPC), Ansible will have a hard time
        # to add VPC Security Groups - groan - unless you fiddle with ec2_eni module
        group_id: "{{ sg_group_id | default(omit) }}"
        instance_type: "{{ ec2_instance_type }}"
        image: "{{ ec2_image }}"
        vpc_subnet_id: "{{ item.subnet_id }}"
        region: "{{ ec2_region }}"
        instance_tags: '{"Type":"{{ec2_instance_type}}", "Role":"{{ec2_role}}"}'
        assign_public_ip: "{{ item.map_public_ip_on_launch  }}"
        wait: true
        exact_count: "{{ ec2_count }}"
        count_tag:
          Role: "{{ ec2_role }}"
        volumes:
          - device_name: /dev/xvda
            volume_type: gp2
            volume_size: "{{ ec2_volume_size }}"
            delete_on_termination: true
      register: ec2
      with_items: "{{ mysubnets.subnets }}"

    - name: "Add {{ ec2_keypair }}.pem to SSH keychain for the ping"
      shell: "ssh-add keys/{{ ec2_keypair }}.pem"

    - name: Try to ping public instances using public IP
      wait_for: host={{item}} port=22 delay=60 timeout=300 state=started
      with_items: "{{ec2|json_query('results[*].instances[*].public_ip')}}"
      when: ec2_bastion is not defined

    - name: Try to ping private instances using private IP
      delegate_to: "{{ ec2_bastion }}"
      wait_for: host={{item}} port=22 delay=60 timeout=300 state=started
      with_items: "{{ec2|json_query('results[*].instances[*].private_ip')}}"
      when: ec2_bastion is defined
