---
### ping an AWS EC2 instance into a specified region and role configured in an instance type
### example:
### ansible-playbook ec2_ping_by_region_role.yml -e "ec2_region=us-east-1 ec2_role=AdminJumpbox"
### for this to work, the SSH must be working with the key authentication (via ssh-agent or plain file)
### also, the network must be setup (securitygroup, bastion for private network, etc)

- hosts: localhost
  connection: local
  gather_facts: false
  remote_user: ec2-user
  pre_tasks:
    - name: Reads role variables
      include_vars:
        dir: roles/
        files_matching: "{{ ec2_role }}.yml"
  tasks:
    - name: Get EC2 instance IDs
      run_once: true
      ec2_instance_facts:
        region: "{{ ec2_region }}"
        filters:
          "tag:Role": "{{ec2_role}}"
          "instance-state-name": running
      register: ec2

    - name: Try to ping public instances using public IP
      wait_for: host={{item.public_ip_address}} port=22 delay=60 timeout=300 state=started
      with_items: "{{ ec2.instances }}"
      when: ec2_bastion is not defined

    - name: Try to ping private instances using private IP
      delegate_to: "{{ ec2_bastion }}"
      wait_for: host={{item.private_ip_address}} port=22 delay=60 timeout=300 state=started
      with_items: "{{ ec2.instances }}"
      when: ec2_bastion is defined
