---
### Runs a yum update on a set of selected instances by region and role
### example:
### ansible-playbook ec2_yum_update_by_region_role.yml -e "ec2_region=us-east-1 ec2_role=AdminJumpbox"

- hosts: localhost
  connection: local
  gather_facts: false
  user: root
  tasks:
    - name: Get EC2 instance IDs
      run_once: true
      ec2_instance_facts:
        region: "{{ ec2_region }}"
        filters:
          "tag:Role": "{{ec2_role}}"
          "instance-state-name": running
      register: instances

    - name: "Fetch instances IP adresses in the region {{ ec2_region }}"
      debug:
        msg: "IP: {{item}}"
      with_items: "{{instances|json_query('instances[*].public_ip_address')}}"

    - add_host:
        name: "{{ item }}"
        groups: to_update
      with_items: "{{instances|json_query('instances[*].public_ip_address')}}"

- hosts: to_update
  gather_facts: false
  user: ec2-user
  tasks:
  - name: upgrade all packages
    become: true
    yum:
      use_backend: yum 
      name: '*'
      state: latest
