---
### Lists all EC2 machines currently provisioned

- hosts: localhost
  connection: local
  gather_facts: false
  user: root
  tasks:
    - name: Get EC2 instance IDs
      run_once: true
      ec2_instance_facts:
      register: instances

    - name: List Instances
      debug:
        msg: "Statuses: {{item.state}}"
      with_items:
        - { instanceId: "{{instances|json_query('instances[*].instance_id')}}", state: "{{instances|json_query('instances[*].state.name')}}" }
      loop_control:
        label: "{{ item.instanceId}}"
