---
### Runs a yum to install packages described in the roles file
#### The instance must have SSH access using keys, open port in Security Group, etc...
### example:
### ansible-playbook ec2_yum_install_packages_by_role.yml -e "ec2_region=us-east-1 ec2_role=WPServer"

- hosts: localhost
  connection: local
  gather_facts: false
  pre_tasks:
    - name: Reads role variables
      include_vars:
        dir: roles/
        files_matching: "{{ ec2_role }}.yml"
  tasks:
    - name: Get EC2 instance IDs
      run_once: true
      ec2_instance_facts:
        region: "{{ ec2_region }}"
        filters:
          "tag:Role": "{{ec2_role}}"
          "instance-state-name": running
      register: instances

    - name: "Fetch instances Public IP adresses in the region {{ ec2_region }}"
      debug:
        msg: "IP: {{item}}"
      with_items: "{{instances|json_query('instances[*].public_ip_address')}}"
      when: ec2_bastion is not defined

    - name: "Fetch instances Public IP adresses in the region {{ ec2_region }}"
      debug:
        msg: "IP: {{item}}"
      with_items: "{{instances|json_query('instances[*].public_ip_address')}}"
      when: ec2_bastion is defined

    - add_host:
        name: "{{ item }}"
        groups: to_update
      with_items: "{{instances|json_query('instances[*].public_ip_address')}}"
      when: ec2_bastion is not defined

    - add_host:
        name: "{{ item }}"
        groups: to_update
      with_items: "{{instances|json_query('instances[*].private_ip_address')}}"
      when: ec2_bastion is defined

- hosts: to_update
  gather_facts: false
  user: ec2-user
  pre_tasks:
    - name: Reads role variables
      include_vars:
        dir: roles/
        files_matching: "{{ ec2_role }}.yml"
  tasks:
  - name: Install and upgrade all packages
    become: true
    yum:
      use_backend: yum 
      name: "{{ yum_packages }}" 
      state: latest

  - name: Restart service httpd, in all cases
    become: true
    service:
      name: httpd
      state: restarted
    when: '"httpd" in yum_packages'
