---
### Lists facts about a RDS instance
### ansible-playbook rds_get_facts.yml -e "ec2_region=us-east-1 rds_instance_name=wordpressdb"

- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Get facts about "{{ rds_instance_name }}"
      rds:
        region: "{{ ec2_region }}"
        command: facts
        instance_name: "{{ rds_instance_name }}"
      register: database_facts
