---
### Lists Subnets by role
### ansible-playbook vpc_list_subnets_by_role.yml -e "ec2_region=us-east-1 ec2_role=WPServer"

- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: "Get Subnets for {{ ec2_role }}"
      ec2_vpc_subnet_facts:
        region: "{{ ec2_region }}"
        filters:
          "tag:Role": "{{ ec2_role }}"
      register: mysubnets

    - name: List Subnets
      debug:
        var: subnets

    - name: List Subnets
      debug:
        msg: "{{ item.subnet_id }} {{ item.tags.Name }} {{ item.tags.Role }}"
      with_items: "{{ mysubnets.subnets }}"
