---
### Deletes NAT gateway in a given subnet - useful to remove the NAT when you no longer need it
### example:
### ansible-playbook vpc_delete_nat_gateway.yml -e "ec2_region=us-east-1 ec2_subnet=PublicSubnetBastion"

- hosts: localhost
  connection: local
  gather_facts: false
  pre_tasks:
    - name: Reads Subnet variables
      include_vars:
        dir: networks/
        files_matching: "{{ ec2_subnet }}.yml"
  tasks:
    - name: Get nat gateways for "{{ ec2_subnet }}"
      ec2_vpc_nat_gateway_facts:
        region: "{{ ec2_region }}" 
        filters:
          subnet-id: "{{ ec2_subnet_id }}"
          state: ['available']
      register: gateways_to_remove

    - name: Delete nat gateway using discovered nat gateways from facts module.
      ec2_vpc_nat_gateway:
        state: absent
        region: "{{ ec2_region }}"
        wait: yes
        nat_gateway_id: "{{ item.nat_gateway_id }}"
        release_eip: yes
      register: delete_nat_gateway_result
      with_items: "{{ gateways_to_remove.result }}"

    - name: remove NAT gw files
      file:
        path: "networks/{{ ec2_subnet }}_{{ item.nat_gateway_id }}"
        state: absent
      with_items: "{{ gateways_to_remove.result }}"
