ec2_instance_type: "t2.micro"
ec2_image: "ami-0080e4c5bc078760e"
ec2_keypair: "bastionkeypair"
ec2_volume_size: 8
ec2_count: 1
ec2_bastion: "18.215.243.60"
ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q ec2-user@18.215.243.60"'
